# Time in seconds between envoy spawns
envoy-spawn-interval: 60

# Time in seconds before an envoy despawns automatically
despawn-timer: 30

# Minimum and maximum number of envoys to spawn each interval
min_envoy: 1
max_envoy: 10

# Specific fixed spawn points by world name
envoy-spawn-locations:
  world:
    - x: 1
      y: 70
      z: 1
    - x: 2
      y: 70
      z: 2
    - x: 3
      y: 70
      z: 3
