# Time in seconds between envoy spawns
envoy-spawn-interval: 60

# Time in seconds before an envoy despawns automatically
despawn-timer: 20

# Minimum and maximum number of envoys to spawn each interval
min_envoy: 1
max_envoy: 10

# Specific fixed spawn points by world name
envoy-spawn-locations:
  world:
    - x: 5
      y: 4
      z: 5
    - x: 7
      y: 4
      z: 7
    - x: 3
      y: 4
      z: 3
