# Interval in seconds between envoy spawns
envoy-spawn-interval: 60

# Time in seconds before an envoy despawns
despawn-timer: 30

# Minimum number of envoys to spawn each interval
min_envoy: 1

# Maximum number of envoys to spawn each interval
max_envoy: 5

# Exact envoy spawn locations with world names and coordinates
envoy-spawn-locations:
  spawn1:
    world: world
    x: 100
    y: 65
    z: 200
